# Hexo é…ç½®æ–‡ä»¶
## æ–‡æ¡£: https://hexo.io/docs/configuration.html
## æºç : https://github.com/hexojs/hexo/

# ç½‘ç«™è®¾ç½®
title: lycanClaw
subtitle: 'æ¸Šç—•çˆªè¿¹'
description: 'ç»´å…‹ç½—å¾·çš„ä¸–ç•Œæ¢ç´¢ç¬”è®°ğŸ§­'
keywords: 
author: Wreckloud
language: zh-CN
timezone: Asia/Shanghai

# ç½‘å€è®¾ç½®
## åœ¨æ­¤è®¾ç½®æ‚¨çš„ç½‘ç«™ç½‘å€ã€‚ä¾‹å¦‚ï¼Œå¦‚æœæ‚¨ä½¿ç”¨GitHub Pagesï¼Œè¯·å°†ç½‘å€è®¾ç½®ä¸º'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # è®¾ç½®ä¸ºfalseå¯ä»¥ä»æ°¸ä¹…é“¾æ¥ä¸­åˆ é™¤å°¾éƒ¨çš„'index.html'
  trailing_html: true # è®¾ç½®ä¸ºfalseå¯ä»¥ä»æ°¸ä¹…é“¾æ¥ä¸­åˆ é™¤å°¾éƒ¨çš„'.html'

# ç›®å½•è®¾ç½®
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# å†™ä½œè®¾ç½®
new_post_name: :title.md # æ–°æ–‡ç« çš„æ–‡ä»¶åæ ¼å¼
default_layout: post
titlecase: false # å°†æ ‡é¢˜è½¬æ¢ä¸ºæ ‡é¢˜æ ¼å¼
external_link:
  enable: true # åœ¨æ–°æ ‡ç­¾é¡µä¸­æ‰“å¼€å¤–éƒ¨é“¾æ¥
  field: site # åº”ç”¨äºæ•´ä¸ªç½‘ç«™
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# é¦–é¡µè®¾ç½®
# path: åšå®¢ç´¢å¼•é¡µçš„æ ¹è·¯å¾„ï¼ˆé»˜è®¤ä¸º''ï¼‰
# per_page: æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°ï¼ˆ0 = ç¦ç”¨åˆ†é¡µï¼‰
# order_by: æ–‡ç« æ’åºæ–¹å¼ï¼ˆé»˜è®¤æŒ‰æ—¥æœŸé™åºæ’åˆ—ï¼‰
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# åˆ†ç±» & æ ‡ç­¾
default_category: uncategorized
category_map:
tag_map:

# å…ƒæ•°æ®å…ƒç´ 
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# æ—¥æœŸ / æ—¶é—´æ ¼å¼
## Hexoä½¿ç”¨Moment.jsè§£æå’Œæ˜¾ç¤ºæ—¥æœŸ
## æ‚¨å¯ä»¥æŒ‰ç…§http://momentjs.com/docs/#/displaying/format/ä¸­å®šä¹‰çš„æ ¼å¼è‡ªå®šä¹‰æ—¥æœŸæ ¼å¼
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_optionæ”¯æŒ'mtime'ã€'date'ã€'empty'
updated_option: 'mtime'

# åˆ†é¡µ
## å°†per_pageè®¾ç½®ä¸º0ä»¥ç¦ç”¨åˆ†é¡µ
per_page: 10
pagination_dir: page

# åŒ…å«/æ’é™¤æ–‡ä»¶
## include:/exclude:é€‰é¡¹ä»…é€‚ç”¨äº'source/'æ–‡ä»¶å¤¹
include:
exclude:
ignore:

# æ‰©å±•
## æ’ä»¶: https://hexo.io/plugins/
## ä¸»é¢˜: https://hexo.io/themes/
theme: redefine

# éƒ¨ç½²
## æ–‡æ¡£: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
